### ISSUE TITLE
Add a way to paste stdin

### ISSUE THREAD

**Issue by Julian** [supakeen/steck#15]
Hi!

It'd be nice if it were possible to pipe data into steck directly (similar to the [old bpaste script we had](https://github.com/Julian/dotfiles/blob/main/bin/bpaste).

I.e.::

```
seq 10 | steck paste
```

As is, it doesn't look like it's even possible to do this by explicitly passing `/dev/stdin`, as in `seq 10 | steck paste /dev/stdin`, because [this line](https://github.com/supakeen/steck/blob/b1982ce493b63052373cf3e97f388c90871db7e0/steck.py#L60) will be `False` for `/dev/stdin`, which isn't itself a file.

**Comment by supakeen** [comment]
Yea, this is useful, I'll probably do the magic `-` filename which some GNU tools use to denote stdin?
