### ISSUE TITLE
Request for tag/release

### ISSUE THREAD

**Issue by NeilHanlon** [supakeen/steck#24]
Hiya :) Myself and @SherifNagy are working on packaging steck for Fedora, and noticed there has not been a release in some time. Due to how it is being packaged (i.e., with the python macros in RPM), it is detected as a "legacy" package due to the most recent version on PyPi being 0.7.0, which still has a setup.py instead of the pyproject.toml/PEP-517 format.

I'm happy to help out with anything you need!

Best,
Neil

**Comment by supakeen** [comment]
I'll tag and upload a release over the weekend.

**Comment by supakeen** [comment]
Done with 0.8.0.
